# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD, Build & deploy for all modules

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  PROJECT_NAME: 'spcm032'
  AZURE_RESOURCE_GROUP_NAME: 'spcm032-rg'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_LOCATION: 'westus'

  ASC_PACKAGE_PATH: ${{ github.workspace }}

  SPRING_CLOUD_SERVICE: spcm032-springcloud

  API_GATEWAY: api-gateway
  ADMIN_SERVER: admin-server
  CUSTOMERS_SERVICE: customers-service
  VETS_SERVICE: vets-service
  VISITS_SERVICE: visits-service
  CONSUMER_SERVICE: consumer-service

  API_GATEWAY_JAR: spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-2.5.1.jar
  ADMIN_SERVER_JAR: spring-petclinic-admin-server/target/spring-petclinic-admin-server-2.5.1.jar
  CUSTOMERS_SERVICE_JAR: spring-petclinic-customers-service/target/spring-petclinic-customers-service-2.5.1.jar
  VETS_SERVICE_JAR: spring-petclinic-vets-service/target/spring-petclinic-vets-service-2.5.1.jar
  VISITS_SERVICE_JAR: spring-petclinic-visits-service/target/spring-petclinic-visits-service-2.5.1.jar  
  CONSUMER_SERVICE_JAR: spring-petclinic-consumer/target/spring-petclinic-consumer-2.5.1.jar  

  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS02 }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  KEYVAULT_URI: https://spcm032-keyvault.vault.azure.net/  

  AZURE_CRED: ${{ secrets.AZURE_CREDENTIALS01 }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Login via Azure CLI
        uses: azure/login@v1.1
        with:
          creds: ${{ env.AZURE_CRED }}

      - name: Run script file
        run: |
           jq --version

           KEY0=`az redis list-keys --name ${{ env.PROJECT_NAME }}-redis --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} | jq -r .primaryKey`
           echo "{\"singleServerConfig\":{\"address\": \"redis://${{ env.PROJECT_NAME }}-redis.redis.cache.windows.net:6379\", \"password\": \"$KEY0\"}}" > redisson.json
           cat redisson.json

           cp redisson.json spring-petclinic-${{ env.CUSTOMERS_SERVICE }}/src/main/resources/
           cp redisson.json spring-petclinic-${{ env.VETS_SERVICE }}/src/main/resources/
           cp redisson.json spring-petclinic-${{ env.VISITS_SERVICE }}/src/main/resources/

        shell: bash

      - name: maven build, clean
        run: |
          mvn -B package -DskipTests -Denv=cloud
          
      - name: deploy to production with artifact, api-gateway
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.API_GATEWAY }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.API_GATEWAY_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql

      - name: deploy to production with artifact, admin-server
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.ADMIN_SERVER }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.ADMIN_SERVER_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql

      - name: deploy to production with artifact, customers-service 
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.CUSTOMERS_SERVICE }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.CUSTOMERS_SERVICE_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql
          environment-variables: "-AZURE_CLIENT_ID ${{ env.AZURE_CLIENT_ID }} -AZURE_CLIENT_SECRET ${{ env.AZURE_CLIENT_SECRET }} -AZURE_TENANT_ID ${{ env.AZURE_TENANT_ID }} -KEYVAULT_URI ${{ env.KEYVAULT_URI }}"

      - name: deploy to production with artifact, vets-service
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.VETS_SERVICE }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.VETS_SERVICE_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql
          environment-variables: "-AZURE_CLIENT_ID ${{ env.AZURE_CLIENT_ID }} -AZURE_CLIENT_SECRET ${{ env.AZURE_CLIENT_SECRET }} -AZURE_TENANT_ID ${{ env.AZURE_TENANT_ID }} -KEYVAULT_URI ${{ env.KEYVAULT_URI }}"

      - name: deploy to production with artifact, visits-service 
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.VISITS_SERVICE }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.VISITS_SERVICE_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql
          environment-variables: "-AZURE_CLIENT_ID ${{ env.AZURE_CLIENT_ID }} -AZURE_CLIENT_SECRET ${{ env.AZURE_CLIENT_SECRET }} -AZURE_TENANT_ID ${{ env.AZURE_TENANT_ID }} -KEYVAULT_URI ${{ env.KEYVAULT_URI }}"

      - name: deploy to production with artifact, consumer-service
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          action: Deploy
          service-name: ${{ env.SPRING_CLOUD_SERVICE }}
          app-name: ${{ env.CONSUMER_SERVICE }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/${{ env.CONSUMER_SERVICE_JAR }}
          jvm-options: -Xms2048m -Xmx2048m -Dspring.profiles.active=mysql
          environment-variables: "-AZURE_CLIENT_ID ${{ env.AZURE_CLIENT_ID }} -AZURE_CLIENT_SECRET ${{ env.AZURE_CLIENT_SECRET }} -AZURE_TENANT_ID ${{ env.AZURE_TENANT_ID }} -KEYVAULT_URI ${{ env.KEYVAULT_URI }}"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout
